// @vitest-environment node
/**
 * The brand icon set (#504), generated by scripts/brand-icons.mjs from the navbar logo mark:
 * every icon is square at its declared size (read from the PNG header, as og-assets.ts does),
 * there is one favicon set, and the maskable icon keeps the mark inside the safe zone.
 */
import { describe, expect, it } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { inflateSync } from 'node:zlib';
import manifest from './manifest';
import { rootMetadata } from '@/lib/metadata';
import { BRAND_DARK } from '@/lib/brand-palette';

const appDir = dirname(fileURLToPath(import.meta.url));
const publicDir = join(appDir, '../../public');

/** Width and height from a PNG's IHDR chunk (after the 8-byte signature and chunk header). */
function pngSize(png: Buffer): { w: number; h: number } {
  expect([...png.subarray(0, 8)]).toEqual([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
  return { w: png.readUInt32BE(16), h: png.readUInt32BE(20) };
}

/** Decode an 8-bit RGBA, non-interlaced PNG (what the generator writes) into raw pixels. */
function decodeRgba(png: Buffer): { w: number; h: number; px: Uint8Array } {
  const { w, h } = pngSize(png);
  expect([png[24], png[25], png[28]], 'bit depth, colour type, interlace').toEqual([8, 6, 0]);
  const idat: Buffer[] = [];
  for (let i = 8; i < png.length; ) {
    const len = png.readUInt32BE(i);
    if (png.toString('latin1', i + 4, i + 8) === 'IDAT')
      idat.push(png.subarray(i + 8, i + 8 + len));
    i += 12 + len;
  }
  const raw = inflateSync(Buffer.concat(idat));
  const stride = w * 4;
  const px = new Uint8Array(h * stride);
  for (let y = 0; y < h; y++) {
    const filter = raw[y * (stride + 1)];
    for (let x = 0; x < stride; x++) {
      const cur = raw[y * (stride + 1) + 1 + x];
      const a = x >= 4 ? px[y * stride + x - 4] : 0;
      const b = y > 0 ? px[(y - 1) * stride + x] : 0;
      const c = x >= 4 && y > 0 ? px[(y - 1) * stride + x - 4] : 0;
      const p = a + b - c;
      const paeth =
        Math.abs(p - a) <= Math.abs(p - b) && Math.abs(p - a) <= Math.abs(p - c)
          ? a
          : Math.abs(p - b) <= Math.abs(p - c)
            ? b
            : c;
      const pred = [0, a, b, (a + b) >> 1, paeth][filter];
      px[y * stride + x] = (cur + pred) & 0xff;
    }
  }
  return { w, h, px };
}

const hex = (r: number, g: number, b: number) =>
  `#${[r, g, b].map((v) => v.toString(16).padStart(2, '0')).join('')}`.toUpperCase();

const publicFile = (src: string) => readFileSync(join(publicDir, src.replace(/^\//, '')));

describe('brand icons (#504)', () => {
  const icons = manifest().icons ?? [];

  it('every manifest icon is a square PNG at its declared size', () => {
    expect(icons.length).toBeGreaterThanOrEqual(3);
    for (const icon of icons) {
      const [w, h] = (icon.sizes ?? '').split('x').map(Number);
      expect(w, icon.src).toBe(h);
      expect(pngSize(publicFile(icon.src)), icon.src).toEqual({ w, h });
    }
  });

  it('ships a real maskable icon, not a copy of the regular one', () => {
    const maskable = icons.find((i) => i.purpose === 'maskable');
    const regular = icons.find((i) => i.sizes === maskable?.sizes && i.purpose !== 'maskable');
    expect(maskable && regular).toBeTruthy();
    expect(publicFile(maskable!.src).equals(publicFile(regular!.src))).toBe(false);
  });

  it('keeps the maskable mark inside the 80% safe zone, on a full-bleed opaque tile', () => {
    const src = icons.find((i) => i.purpose === 'maskable')!.src;
    const { w, h, px } = decodeRgba(publicFile(src));
    const bg = BRAND_DARK.background.toUpperCase();
    const translucent: string[] = [];
    const markOutside: string[] = [];
    let markInside = 0;
    for (let y = 0; y < h; y++) {
      for (let x = 0; x < w; x++) {
        const i = (y * w + x) * 4;
        if (px[i + 3] !== 255) translucent.push(`${x},${y}`);
        // maskable.app's minimum safe zone: a circle of radius 40% of the icon, centred.
        const outside = Math.hypot(x + 0.5 - w / 2, y + 0.5 - h / 2) > 0.4 * w;
        const isBg = hex(px[i], px[i + 1], px[i + 2]) === bg;
        if (outside && !isBg) markOutside.push(`${x},${y}`);
        if (!outside && !isBg) markInside++;
      }
    }
    expect(translucent).toEqual([]);
    expect(markOutside).toEqual([]);
    expect(markInside).toBeGreaterThan(0); // the mark is really there
  });

  it('serves a 180px Apple touch icon from app/apple-icon.png', () => {
    expect(pngSize(readFileSync(join(appDir, 'apple-icon.png')))).toEqual({ w: 180, h: 180 });
  });

  it('favicon.ico holds square 16, 32 and 48px PNGs', () => {
    const ico = readFileSync(join(appDir, 'favicon.ico'));
    expect([ico.readUInt16LE(0), ico.readUInt16LE(2)]).toEqual([0, 1]);
    const sizes = Array.from({ length: ico.readUInt16LE(4) }, (_, n) => {
      const e = 6 + 16 * n;
      const png = ico.subarray(
        ico.readUInt32LE(e + 12),
        ico.readUInt32LE(e + 12) + ico.readUInt32LE(e + 8),
      );
      const { w, h } = pngSize(png);
      expect([ico[e], ico[e + 1]]).toEqual([w, h]);
      return `${w}x${h}`;
    });
    expect(sizes).toEqual(['16x16', '32x32', '48x48']);
  });

  it('icon.svg is the navbar logo mark in the dark-theme token colours', () => {
    const svg = readFileSync(join(appDir, 'icon.svg'), 'utf8');
    const logo = readFileSync(join(appDir, '../components/brand/logo.tsx'), 'utf8');
    expect(svg).toMatch(/viewBox="0 0 32 32"/);
    for (const shape of [
      'points="5,8 12,5 18,11 9,18"',
      'cx="12" cy="5" r="2"',
      'cx="5" cy="8" r="1.4"',
      'cx="18" cy="11" r="1.4"',
      'cx="9" cy="18" r="1.4"',
    ]) {
      expect(logo, shape).toContain(shape);
      expect(svg, shape).toContain(shape);
    }
    const colours = new Set([...svg.matchAll(/#[0-9A-Fa-f]{6}/g)].map((m) => m[0].toUpperCase()));
    expect(colours).toEqual(
      new Set([BRAND_DARK.background, BRAND_DARK.starlight, BRAND_DARK.violet]),
    );
  });

  it('declares no metadata icons, so the page carries one favicon set (the app/ icon files)', () => {
    expect(rootMetadata.icons).toBeUndefined();
    for (const file of ['favicon.ico', 'icon.svg', 'apple-icon.png']) {
      expect(existsSync(join(appDir, file)), file).toBe(true);
    }
  });
});
